---
- hosts: all
  remote_user: ubuntu
  become: true
  become_method: sudo
  roles:
      - deploy-contactmerge
      - deploy-monitor_throttler
      - deploy-logger_processor
      - deploy-email_sync
      - deploy-indexer 

